### ISSUE TITLE
Inconsistent results on two versions

### ISSUE THREAD

**Issue by Heaven2024** [cvc5/cvc5#11066]
[test.txt](https://github.com/user-attachments/files/16276539/test.txt)

[test2.txt](https://github.com/user-attachments/files/16276540/test2.txt)

These two cases come from actual applications. The solution result of z3 and cvc5 1.1.2 is unsat, but in cvc5 1.1.3 it returns sat.

This is cvc5 version 1.1.3-dev.291.900587976 [git 900587976 on branch main]
```
cvc5 test.smt2 -q
sat
cvc5 test2.smt2 -q
sat

cvc5-1.1.2 test.smt2 -q
unsat
```

**Comment by ajreynol** [comment]
Minimized example:
```
(set-logic ALL)
(assert (exists ((x Real))
          (let ((?y x))
          (and (<= 0 x) (exists ((x Real)) (forall ((v Real)) (> 0 ?y)))))))
(check-sat)

**Comment by barrettcw** [comment]
According to the SMT-LIB standard, the right thing to do is to rename the second instance of the bound variable x so that when ?y is replaced by x, there is no variable capture.

**Comment by HanielB** [comment]
The issue is exactly that cvc5 does not apply the capture-avoiding substitution in the parser. This was not an issue before because cvc5 generated fresh variables for each variable binding during parser (so the `x` in the outermost quantifier was not the same from the one in the innermost quantifier),  which amounts to "renaming everything" during parsing, so there would never be capture anyway. The PR #11076 will re-introduce this behavior to eliminate the soundness issue (but we will still have to find a solution for the use cases that benefit of creating the same variable for both `x`s above, which are proofs and distributed solving).
