### ISSUE TITLE
Unexpected behavior regarding division by zero

### ISSUE THREAD

**Issue by Heaven2024** [cvc5/cvc5#11211]
Hi!
cvc5 version 1.2.1-dev.25.7b50b6ee65 [git 7b50b6ee65 on branch main]
ubuntu:22.04

```
(set-logic QF_LRA)
(declare-fun x () Real)
(assert (= x (/ 1.0 0.0)))
(check-sat)
(get-model)

cvc5 xx.smt2 --produce-models
sat
(
(define-fun x () Real (/ 1.0 0.0))
) 
```
When added` --check-models`,it returns:
```
(error "A non-linear fact was asserted to arithmetic in a linear logic.
The fact in question: (/ 1.0 0.0)
")
```
Also, I want to know, is division by 0 legal in this case?

**Comment by ajreynol** [comment]
No, division by zero is considered to be non-linear arithmetic.

The reason why cvc5 is not complaining in the first case is that it happens to remove the division by zero constraint during preprocessing.  In general, cvc5 in some cases does not throw logic exceptions eagerly if the constraints can be removed in this manner.

So, this is expected behavior.
