### ISSUE TITLE
SMT2 parser accepts quote char (') from file but not from stdin

### ISSUE THREAD

**Issue by 4tXJ7f** [cvc5/cvc5#1862]
```
$ cat print.smt2
(set-option :incremental false)
(set-info :source "ABC
ABC'00
http://www.xx.x.x.x/x/")
$ cat print.smt2 | builds/bin/cvc4 --lang=smt2
(error "Parse Error: <stdin>:3.23: Extended/unprintable characters are not part of SMT-LIB, and they must be encoded as escape sequences")
$ builds/bin/cvc4 --lang=smt2 print.smt2
$
```

Note: The issue might be a bit more complicated than it seems because changing the non-quote chars in the string can change the error message to:

```
$ cat print.smt2
(set-option :incremental false)
(set-info :source "ABC
ABC'00
http://www.x.x.x/x/")
$ cat print.smt2 | builds/bin/cvc4 --lang=smt2
(error "Parse Error: <stdin>:3.20: basic_string::_M_create")
```

**Comment by nafur** [comment]
I found that this is caused by buffering lines. Actually, `--asan` triggers in `AntlrInput::tokenText` because the token spans multiple lines but the next line has not been read yet (`getStopIndex()` returns a pointer beyond the current buffer).
One fix is to disable line buffering altogether, for example by passing `false` instead of `lineBuffered` at https://github.com/CVC4/CVC4/blob/master/src/parser/input.cpp#L72.
Is there anything about line buffering that makes it important to us? It really seems to arbitrarily introduce problems into our parsing process...
