### ISSUE TITLE
Please provide a way to build the python binding separately

### ISSUE THREAD

**Issue by yurivict** [cvc5/cvc5#2189]
We can have multiple versions of python installed at the same time on FreeBSD. Each python version needs its own binding package.

Could you please either split the binding out into a separate project, or document how to build only the binding once the rest of the project is installed?

Thank you.

**Comment by 4tXJ7f** [comment]
Let me make sure that I understand your request correctly: You would like to be able to compile CVC4 once and then after that compile the bindings for different versions of Python after that? So configuring and compiling the whole project for each Python version is not an option? It might take a while to have a way to just compile the bindings for different versions but I'll investigate if there is an easy solution. One issue is that we are planning to have nicer Python bindings in the future that are not generated with SWIG, so I don't know how much effort we can dedicate to the existing bindings. Also, do you have an example of a project that solves this in a good fashion? Thanks!

**Comment by yurivict** [comment]
> Let me make sure that I understand your request correctly ...

Yes, this is what I want.

>  Also, do you have an example of a project that solves this in a good fashion?

For example, llvmcpy: https://github.com/revng/llvmcpy It is the standalone llvm binding. llvm has an incredibly large and complex interface, and they build the binding using ```py-cffi```. As I understand it, it builds the binding off of the C++ library.

**Comment by 4tXJ7f** [comment]
Cool, thanks! I'll have a look.

**Comment by nafur** [comment]
I'm sorry to say that we will not support this.

The technical reason is that migrating an existing build folder to another python version is surprisingly tricky because of all the different layers of caching of configuration and build artifacts. I tried it, but pretty quickly got into the business of manually overriding stuff in the cmake cache that is not meant for a regular user, and then having to manually remove build artifacts that need to be rebuilt.
Our solution (and also the guidance I would offer) is to use ccache and build from scratch for every python version using the `mk_clean_wheel.sh` script from https://github.com/cvc5/cvc5/tree/master/contrib/packaging_python.
Using ccache reduces the overhead to less than a minute per rebuild, which is acceptable for us.
