### ISSUE TITLE
Assertion `!locked(c)` fails with unsat cores on incremental inputs

### ISSUE THREAD

**Issue by 4tXJ7f** [cvc5/cvc5#3455]
On three of our regressions:
- regress1/push-pop/arith_lra_01.smt2
- regress1/push-pop/fuzz_3_9.smt2 
- regress1/push-pop/fuzz_3_6.smt2 

The following assertion failure occurs when using `--incremental --check-unsat-cores`:
```
cvc4: /home/noetzli/CVC4_asan/src/prop/minisat/core/Solver.cc:1192: void CVC4::Minisat::Solver::removeClausesAboveLevel(CVC4::Minisat::vec<unsigned int>&, int): Assertion `!locked(c)' failed.                                                                                  
```

**Comment by nafur** [comment]
This still happens with
```
(declare-fun x0 () Real)
(check-sat)
(assert (<= (* x0 (- 1)) 0))
(assert (or (>= 0 x0) (> (+ 1.0 x0) (- 12))))
(check-sat)
(push)
(assert (<= x0 (- 13)))
(check-sat)
(check-sat)
(check-sat)
```

**Comment by HanielB** [comment]
As an internal note, in proof-new the issue is fixed for the regressions
- regress1/push-pop/arith_lra_01.smt2
- regress1/push-pop/fuzz_3_9.smt2
- regress1/push-pop/fuzz_3_6.smt2
but still broken for the above example @nafur posted. This is due to the known issue of *not* adding explanations in the optimal level, which is disabled in incremental.

**Comment by rainoftime** [comment]
~~~~
(set-option :produce-unsat-cores true)
(declare-fun x1 () Real)
(declare-fun x2 () Real)
(assert (= 0 x2))
(assert (or (= 1 x1) (= x2 1)))
(check-sat)
(push)
(assert (= 0 x1))
(check-sat)
~~~~

**Comment by nafur** [comment]
While the example fromhttps://github.com/CVC4/CVC4/issues/3455#issuecomment-664980322 works now, the last one still fails.
