### ISSUE TITLE
get-abc script fails on mac

### ISSUE THREAD

**Issue by dddejan** [cvc5/cvc5#4654]
Not really sure what's going on. This is on Catalina 10.15.5 with brew, nothing special just up-to-date.

```console
$ ./contrib/get-abc
...
Copying libabc.a to /Users/dejan/workspace/CVC4/deps/install/lib
Copying arch_flags to /Users/dejan/workspace/CVC4/deps/install/bin
cp: illegal option -- -
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
```

**Comment by nafur** [comment]
I would **guess** that this is due to `cp --parents` [here](https://github.com/CVC4/CVC4/blob/master/contrib/get-abc#L34). MacOS's cp simply does not support this options, see also [this stackoverflow thread](https://stackoverflow.com/questions/11246070/cp-parents-option-on-mac).
Suggestions from this thread are `ditto` or `rsync`.

**Comment by ajreynol** [comment]
This file no longer exists, closing.
