### ISSUE TITLE
CVC4's parser does not support the full set of printable characters for piped symbols.

### ISSUE THREAD

**Issue by aniemetz** [cvc5/cvc5#4746]
CVC4's parser does not support the full set of printable characters for piped symbols (decimal 32-126 and 128-255 as defined in the SMT-LIB2 standard).

[smtmbt-973974500.smt2.zip](https://github.com/CVC4/CVC4/files/4922342/smtmbt-973974500.smt2.zip)

**Comment by ajreynol** [comment]
As far as I can tell, the attached benchmark should be rejected since it contains a `|` inside the consecutive characters surrounded by `|...|` (line 2, column 111).  If this is removed, the benchmark is parsed properly, both by the ANTLR parser and the new Flex parser.  z3 has the same behavior as well.
