### ISSUE TITLE
Mixing the finite relations extension with built-in types

### ISSUE THREAD

**Issue by johndoe888** [cvc5/cvc5#6166]
**Describe the bug**
Mixing the finite relations extension with built-in types as CVC4 is stated to support in the paper "Relational Constraint Solving in SMT" from Meng et al. (Chapter 5.1 on page 10) quickly leads to an "unknown" result by the solver. Is this a bug, am I doing this wrong, or did I misunderstand the paper in the first place?

Here is the code I was trying to feed to the solver (a modified version of the supplemental code to the paper): [ints.cvc.txt](https://github.com/CVC4/CVC4/files/6172259/ints.cvc.txt)

*Note*: If the bug is triggered with an SMT2 input file please minimize it with [ddsmt](https://github.com/aniemetz/ddSMT).

**Command line arguments**: cvc4 --finite-model-find
**CVC4 version/commit**: This is CVC4 version 1.8 compiled with GCC version 5.3.1 20160211 on Aug 25 2020 08:27:39
**Operating system**: Windows 10 64-bit

**`configure.sh` options**
Paste `configure.sh` here.

**`configure.sh` output**
Paste the output of `configure.sh` here.

**Comment by johndoe888** [comment]
Is it that you cannot mix finite and infinite sets in the relational extensions of cvc4?

Introducing a new finite type IntAtom and using them in the relational extensions works out using a uninterpreted function intAtomToInt (as a discovered example in the supplemental cvc4 scripts shows).

Is this the way?

**Comment by ajreynol** [comment]
Sorry for the delay in reply.

Relations can typically be freely combined with finite model finding techniques.

However, the above example leads to "unknown", due to several factors.  First, It is important to note that there are two independent finite model finding techniques in CVC4:
`--finite-model-find`  which treats uninterpreted sorts as finite and minimizes their cardinality (https://homepage.divms.uiowa.edu/~ajreynol/cav13.pdf).
`--fmf-bound` which tries to infer finite ranges for other types.

Both of these options can make a quantified formula have a finite bound, and hence give CVC4 the ability to say "sat".

In your benchmark, the original quantified formula is problematic:
```
ASSERT (FORALL(bdVar_1:Atom, bdVar_2:INT, bdVar_3:INT) : (((bdVar_1, bdVar_2) IS_IN this_A_i) AND ((bdVar_1, bdVar_3) IS_IN this_A_i)) => (bdVar_2 = bdVar_3));
```
Here, the quantification on INT cannot be inferred to be in a finite range, as `--fmf-bound` only checks whether terms are in finite ranges, or explicitly bound by set membership.  It is not quite the case since `bdVar_1` are elements of tuples that are bound.  (More sophisticated techniques could be implemented in CVC4 as future work).

An alternative encoding is this:
```
atomIntTuple : TYPE = [Atom, INT];
ASSERT (FORALL(a1:atomIntTuple, a2:atomIntTuple) : ((a1 IS_IN this_A_i) AND (a2 IS_IN this_A_i) AND a1.0 = a2.0) => (a1.1 = a2.1));
```
Here, `--fmf-bound` can infer the finite ranges for a1 and a2: they are bound by the membership.

However, there is yet another wrinkle: to minimize `this_A_i`, we use a procedure for sets+cardinality (https://homepage.divms.uiowa.edu/~ajreynol/ijcar16b.pdf). This procedure cannot be freely combined with relations, which is the source of the incompleteness. For the alternative encoding above, with `--finite-model-find --fmf-bound -t sets-incomplete` I get:
```
Sets : incomplete because of CARD(this_A PRODUCT ints).
```
The same issue would arise if bounds were properly inferred for the original benchmark.

Summarizing, the combination of cardinality constraints originating from fmf-bound is incomplete when combined with relations. 

I will think a bit more about how to make this case work, perhaps by avoiding the need for reasoning about sets+cardinality.

**Comment by ajreynol** [comment]
Also, in terms of your suggestion, introducing e.g.`IntAtom` as a new sort is definitely a viable option which I often recommend to users.  The advantage is that you don't have to rely on more complex finite model finding techniques (you can use `--finite-model-find` instead of `--fmf-bound`).  However, such encodings may suffer performance-wise since they add an extra level of indirection.

**Comment by johndoe888** [comment]
Thank you for your enlightening explanations on the topic. I tried your suggestions and as you summarized, for the time being the best solution might be to stick with the encoding via an uninterpreted function. Performance, of course, I have yet to test in larger models.

**Comment by ajreynol** [comment]
Closing this issue now, do let me know if you have further questions.
