### ISSUE TITLE
(default) solution soundness issue on string formula with str.replace_re_all 

### ISSUE THREAD

**Issue by zhendongsu** [cvc5/cvc5#6608]
Commit: https://github.com/cvc5/cvc5/commit/0e9fed387aaf5d0cb1844ab20551fbebfcb8893d
OS: Ubuntu 18.04

```
[586] % z3release small.smt2
unsat
[587] % cvc5 -q --check-models small.smt2
sat
[588] % cvc4-1.8 -q --check-models small.smt2
sat
[589] % cat small.smt2
(declare-fun a () String)
(assert (str.in_re a (re.* (str.to_re "z"))))
(assert (str.in_re a (re.* (re.range "a" "u"))))
(assert (not (str.in_re (str.++ a "za") (re.* (re.union (str.to_re "a") (re.++ (re.union (str.to_re "z") (str.to_re "b")) (re.union (str.to_re (str.replace_re_all "z" (str.to_re "") "")) (str.to_re "b")) (re.* (str.to_re "z"))))))))
(check-sat)
[590] % 
```

**Comment by 4tXJ7f** [comment]
Thanks for the report. This looks like a bug in Z3. `(str.replace_re_all "z" (str.to_re "") "")` evaluates to `"z"` because `replace_re_all` does not replace empty matches. If I do this simplification manually, Z3 (4.8.10) answers sat. If I assert cvc5's model (`a = ""`) together with the original input, then Z3 answers `unknown`.

**Comment by 4tXJ7f** [comment]
I am closing the issue for now. Please reopen it if you disagree with my assessment.

**Comment by zhendongsu** [comment]
You're right, Andres; thanks.  I must have make a mistake in checking the model.  Let me file an issue for Z3 instead.
