### ISSUE TITLE
Unexpected error with terms of sort REGLAN.

### ISSUE THREAD

**Issue by aniemetz** [cvc5/cvc5#6987]
The smt2 input below triggers the following error:
```
(error "expecting a string-like term in relation")
```

smt2:
```
(set-logic ALL)
(declare-const x3 Bool)
(declare-const x String)
(check-sat-assuming ((= 0 (ite (= x (str.replace_re x (ite x3 re.none (str.to_re x)) x)) 1 0))))
```
The above is the minimized (with ddSMT) version of
```
(set-logic ALL)
(declare-const _x0 Int)
(declare-const _x1 Int)
(declare-const _x2 String)
(check-sat-assuming ( (= _x0 _x0) (= _x0 _x0) (let ((_let0 (= _x0 _x0)))(let ((_let1 ((_ divisible 2439918139) _x0)))(ite _let0 (> (mod (ite (ite (ite (and _let0 _let1) _let0 (ite (or (= _let0 _let1) _let1) _let0 (xor (distinct _let0 (= (ite _let0 (str.replace_re _x2 (ite (> _x0 (ite _let0 (ite _let1 _x0 _x1) _x0)) (re.union re.none re.none) (str.to_re _x2)) _x2) _x2) _x2)) _let0))) (str.is_digit _x2) _let0) _x0 (- _x0)) _x0) _x0) _let0))) (= _x0 _x0)))
```

**cvc5 version/commit**: a796c4d8461f22aa523edd3031290e0ba03edd60

**Comment by ajreynol** [comment]
This happened to be fixed in https://github.com/cvc5/cvc5/commit/48a1854491c99d61d21482115e18399195d4d365.

The issue was that we were applying extended equality rewrites to equalities over regular expressions, thus triggering the error above when

We now guard all cases of extended rewriting on equalities to string-like terms only.

This benchmark now gives a proper error:
`(error "Regular expression variables are not supported.")`
