### ISSUE TITLE
cvc5 answers unknown on trivially unsat benchmark with quantified datatype

### ISSUE THREAD

**Issue by barrettcw** [cvc5/cvc5#6996]
Here is the example (minimized from a larger example).  z3 reports unsat instantly.

(set-logic ALL)
(declare-datatypes ((@ 0)) (((V))))
(declare-fun I (@ Int) Bool)
(assert (forall ((v @) (i Int)) (! false :qid |outputbpl.122:24| :pattern ((I v i)))))
(check-sat)

**Comment by barrettcw** [comment]
Note that it is sufficient to have *either* :qid or :pattern - you don't need both.

**Comment by ajreynol** [comment]
For reference, we don't eliminate certain quantified formulas since they have special status, e.g. a quantified formula corresponding to a synthesis conjecture or a quantifier elimination query cannot be eliminated since this loses the connection to what the user requested.

However, clearly "qid" and "pattern" should not have this effect. I'll fix the policy to allow such quantified formulas to be eliminated.
