### ISSUE TITLE
(fmf-fun-rlv) Invalid model on QF_UFNRAT

### ISSUE THREAD

**Issue by merlinsun** [cvc5/cvc5#8118]
Hi, 
For this instance, cvc5https://github.com/cvc5/cvc5/commit/cdef52f07aef156ad19dea89862a1b8d4373ea3a (debug build) first encounters performance issue on the default mode, which can also be reproduced on nightly build.
However, z3 gives `sat` in a short time.
```
$ cat delta.smt2
(set-logic ALL)
(declare-sort R 0)
(declare-fun m (R R) Bool)
(declare-fun e () R)
(declare-fun t () R)
(declare-fun v () Real)
(declare-fun x () R)
(assert (= (m x e) (distinct (m x t) (m x x))))
(assert (= v (sin 1.0)))
(check-sat)
$ cvc5-2022-02-17-x86_64-Linux-production delta.smt2 --tlimit=60000 -q
cvc5 interrupted by timeout.
Aborted (core dumped)
$ z3 delta.smt2 -T:1
sat
```
In addition, with the option `--fmf-fun-rlv`, cvc5 yields `sat` but gives an invalid model.
I'm not sure if this is a duplicate of #7938.
```
$ cvc5-2022-02-17-x86_64-Linux-production delta.smt2 --fmf-fun-rlv --check-models
Fatal failure within void cvc5::smt::CheckModels::checkModel(cvc5::theory::TheoryModel*, const cvc5::context::CDList<cvc5::NodeTemplate<true> >&, bool) at /buildbot/ubuntu20-amd64-production/build/src/smt/check_models.cpp:134
Internal error detected SolverEngine::checkModel(): ERRORS SATISFYING ASSERTIONS WITH MODEL:
assertion:     (= v (sin 1.0))
simplifies to: false
expected `true'.
Run with `--check-models -v' for additional diagnostics.
Aborted (core dumped)
```

**Comment by ajreynol** [comment]
We should change our policy on how simplification works with transcendentals.  Currently, since `sin` is "unevaluatable", we forgo eliminating variables whose definition involve them, so `v` cannot be eliminated in this example.

There are several open PRs to fix issues in the transcendental solver (e.g. https://github.com/cvc5/cvc5/pull/8113), I will revisit the model issue when these are merged.

**Comment by merlinsun** [comment]
Thanks! @ajreynol
