### ISSUE TITLE
Not sure if this a Bug or whether it is a feature that is unsupported.

### ISSUE THREAD

**Issue by jparsert** [cvc5/cvc5#8843]
The following problem leads to an error because of "the unknown indexed function and4"

```
(set-logic LIA)
(declare-fun y () Int)
(declare-fun y1 () Int)

(define-funs-rec ( 
        ( and5 ((x!1 Bool) (x!2 Bool) (x!3 Bool) (x!4 Bool) (x!5 Bool)) Bool)
        ( and3 ((x!1 Bool) (x!2 Bool) (x!3 Bool)) Bool)
        ( and4 ((x!1 Bool) (x!2 Bool) (x!3 Bool) (x!4 Bool)) Bool)
    )
    (
        (and ((_ and4 0) x!1 x!2 x!3 x!4) x!5)
        (and x!1 x!2 x!3)
        (and ((_ and3 0) x!1 x!2 x!3) x!4)
    )
)
                  
(assert (=(and5 true true true true true) true))
(check-sat)
```
I thought this may be a problem because of defining multiple functions in one go but according to the SMT standard this should be allowed.

**Comment by jparsert** [comment]
to be honest, I get this smt problem from the z3 python API, and I want to crossref this with CVC5.

**Comment by 4tXJ7f** [comment]
Interesting. It seems that z3 ignores indices when using function symbols that are not indexed. For example, it allows `((_ and 1 2 3) true false)`. cvc5 is more strict and only allows indices on function symbols that expect them, which is why it doesn't parse the example above. Intuitively, cvc5's behavior seems to make more sense to me (and other solvers such as Bitwuzla don't seem to accept something like `((_ and 1 2 3) true false)` either).

Could you post the Python code that you are using for generating the example above? I am wondering if we can change the Python code to dump an SMT2 file that is compatible with other solvers.

**Comment by jparsert** [comment]
It seems like this happens always in z3 here is a simple example:
```
import z3

solv = z3.Solver()
n = z3.Int("n")
f = z3.RecFunction("f", [z3.IntSort(), z3.IntSort()])
z3.RecAddDefinition(f, n, n * 5 )

solv.add(f(n) >= 42)

print(solv.sexpr())```

**Comment by ajreynol** [comment]
This syntax is not supported.  It seems that more recent versions of z3 also complain for the original input:
```
% z3-4.8.10 issue8843.smt2 
(error "line 11 column 40: invalid use of indexed indentifier, unknown builtin function and4")
sat
```
whereas z3-4.8.4 did not throw this warning.
