### ISSUE TITLE
Is it an invalid model bug?

### ISSUE THREAD

**Issue by aur3l14no** [cvc5/cvc5#8875]
`cvc5 --check-models --produce-models test.smt2`

https://github.com/cvc5/cvc5/commit/1b6fa3da6536191e6b69769c99a3994aab09cd4b

Input

``` smt2
(set-logic QF_UFDTLIA)
(declare-datatype MyList (par (T) ((nelem) (cons (hd T) (tl (MyList T))))))

(declare-fun a () (MyList Int))
(assert (> (hd a) 50))
(assert (not (and
  ((_ is cons) a) (not ((_ is nelem) a))
)))
(check-sat)
(get-model)
```

Output

```
Warning : SolverEngine::checkModel(): cannot check simplified assertion : (>= (hd a) 51)
sat
(
(define-fun a () (MyList Int) (as nelem (MyList Int)))
)
```

**Comment by ajreynol** [comment]
No, this warning is expected due to the partial semantics of selectors. Since `hd` is being applied to the nil element after substituting the model, we cannot evaluate the first assertion.  However, the model is indeed correct since `(hd nelem)` can be interpreted as being greater than 50.

We plan to make our `check-models` option more robust to avoid this warning in the future.
