### ISSUE TITLE
finite-model-find seems confused by equals-zero predicate function

### ISSUE THREAD

**Issue by svenssonaxel** [cvc5/cvc5#8888]
**Describe the bug**

Input 1:
```smt2
(set-logic UFLIA)
(set-option :finite-model-find true)
(declare-fun f (Int) Bool)
(assert (forall ((x Int)) (= (f x) (= x 0))))
(assert (forall ((x Int)) (=> (f x) (< x 10))))
(check-sat)
```

Inputs 2, 3, 4 and 5 are obtained from input 1 by substituting `(= x 0)` for `(= x 1)`, `(= x 5)`, `(= x (- 5))` and `(= x (- 12345))` respectively.

Expected output: `sat` in all cases, or perhaps `unknown` in all cases.

Actual output: `unknown` for input 1 and `sat` for the other inputs.

**Command line arguments**: `--lang smt2`
**cvc5 version/commit**: `1.0.1-dev.160.2a397ba9a [git 2a397ba9a on branch main]`
**Operating system**: `Linux d 5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux`

**`configure.sh` options**  
`--auto-download --poly --cln --gpl`

**Comment by ajreynol** [comment]
Thanks for the example. This is expected behavior.  Finite model finding is only guaranteed to answer "sat" for problems that don't have universal quantification over infinite (interpreted) sorts like integers, as used here.

For problems involving simple universal definitions (which are sometimes called macros), you can try this set of options:
`--finite-model-find --macros-quant --macros-quant-mode=all`
This will eagerly expand the definition of `f` when applicable and is generally the best configuration for "sat" when quantifiers are present.
