### ISSUE TITLE
Solving capability compared to alt-ergo-free/z3 (options/enhancements?)

### ISSUE THREAD

**Issue by robby-phd** [cvc5/cvc5#8928]
**Describe the bug**
cvc4 and cvc5 cannot solve the attached query, while alt-ergo-free (2.3.3) produces `unsat`.

Are there cvc4/cvc5 options that can be provided to successfully solve the query? Or perhaps future cvc5 enhancements?

[test.smt2.gz](https://github.com/cvc5/cvc5/files/9031404/test.smt2.gz)

**Command line arguments**: --lang=smt2.6, --full-saturate-quant/--finite-model-find
**cvc5 version/commit**: cvc4 1.8, cvc5 1.0, cvc5 latest (2022-06-30-9480126)
**Operating system**: macOS Monterey 12.4

**Comment by robby-phd** [comment]
Here's another example proving the same verification condition with automatic rewriting employed to simplify the query.

[test-simplified.smt2.gz](https://github.com/cvc5/cvc5/files/9046876/test-simplified.smt2.gz)

Both alt-ergo-free 2.3.3 and z3 4.8.17 (without any option) produce `unsat` on this example, but cvc4 and cvc5 cannot solve it (z3 cannot solve the previous non-simplified example).

**Comment by ajreynol** [comment]
Hi Robby, thanks for the benchmark.  The issue is that cvc5 seems to be getting into a matching loop.

I recommend the option` --enum-inst-interleave`, which will make cvc5's instantiation interleave techniques from this paper: https://homepage.divms.uiowa.edu/~ajreynol/tacas18.pdf
Generally, this option may increase the average number of instantiations for a given problem, but will generally solve more "unsat" instances overall.

With this option, these benchmarks are solved quickly.

**Comment by robby-phd** [comment]
Excellent, thanks!
