### ISSUE TITLE
Unable to compile cvc5 on M1 mac (cmake issue)

### ISSUE THREAD

**Issue by sirwhinesalot** [cvc5/cvc5#9060]
This is probably a stupid mistake on my end but I am unable to solve it. I keep getting the following error whenever I run configure.sh:

```
CMake Error at cmake/Helpers.cmake:222 (file):
  file RELATIVE_PATH must be passed a full path to the file: .
Call Stack (most recent call first):
  src/util/CMakeLists.txt:20 (libcvc5_add_sources)


CMake Error at cmake/Helpers.cmake:222 (file):
  file RELATIVE_PATH must be passed a full path to the file: .
Call Stack (most recent call first):
  src/util/CMakeLists.txt:92 (libcvc5_add_sources)
```

There are a bunch of other errors like this, pretty much in every call to libcvc5_add_sources.

I checked the Helpers.cmake file, the offending line is:

```
file(RELATIVE_PATH
       _rel_path "${PROJECT_SOURCE_DIR}/src" ".")
```

CMake 3.24.0 doesn't seem to like the "."?

**Comment by 4tXJ7f** [comment]
@sirwhinesalot `configure.sh` seems to work fine for me on M1 with CMake 3.24.0 (except for some warnings that should be fixed with #9058). I took a look at the code of `Helpers.cmake` and it does not seem to use `"."` as the second argument (https://github.com/cvc5/cvc5/blame/6de9bb21603f496eb924698a437d0d1cf1492919/cmake/Helpers.cmake#L222-L223). It also doesn't seem that that changed recently. Could you try downloading a fresh copy of the source code and see if that works for you?

**Comment by sirwhinesalot** [comment]
@4tXJ7f 
I forgot to mention that I used the 1.0.1 release from GitHub not the master branch version. I'll check it out give me a sec and I'll get back to you!

**Comment by sirwhinesalot** [comment]
Master works fine, so it's just an issue of the 1.0.1 release. Sorry for not mentioning it before, I'll close the issue.
