### ISSUE TITLE
cvc5 failing with `% SZS status GaveUp for...` on some simple TPTP fof() problems

### ISSUE THREAD

**Issue by logicReasoner** [cvc5/cvc5#9177]
**Describe the bug**
cvc5 failing with `% SZS status GaveUp for...` on some simple TPTP fof() problems. 
The parsing step seems to succeed but then cvc5 seems to fail at the preprocessing (?) step

**Command line arguments**: Command line arguments passed to cvc5 if applicable 
cvc5-Linux --tlimit=30000 --lang tptp PUZ001+1.p
The same results when just preprocessing:
cvc5-Linux --tlimit=30000 --lang tptp --preprocess-only PUZ001+1.p

Reproducible for example with this simple problem: https://www.tptp.org/cgi-bin/SeeTPTP?Category=Problems&Domain=PUZ&File=PUZ001+1.p 
But it also happens with some others.

**cvc5 version/commit**:
This is cvc5 version 1.0.2 [git tag 1.0.2 branch HEAD]
compiled with GCC version 9.4.0
on Aug 26 2022 17:13:12

**Operating system**: Ubuntu Linux

**Comment by ajreynol** [comment]
Hi,
By default, cvc5 uses incomplete techniques for quantified formulas, which may often up after some effort.

If you would prefer that cvc5 put more effort for solving problems with quantified formulas, I would recommend the option `--full-saturate-quant`, which solves the given problem quickly.  

The option enables techniques from this paper: https://homepage.divms.uiowa.edu/~ajreynol/tacas18.pdf.

Hope this helps,
Andy

**Comment by logicReasoner** [comment]
Hi @ajreynol  
Ah, that's an useful option! Thanks for the help
Now, cvc5 indeed returns an answer `Unsatisfiable` but I believe that the answer should be `Theorem` as stated in the problem itself? Is it just some kind of bug in the implementation or does this show the limitations of the techniques from the above paper?
Also, if you change the conjecture to `killed(charles,agatha)`, then the result should be countersatisfiable but cvc5 rather gives up in this case.

**Comment by ajreynol** [comment]
We are currently unable to distinguish Theorem vs Unsatisfiable, since our API does not currently support "formula roles". So we are unable to know if there is a conjecture.   (As I recall, Theorem essentially means "unsatisfiable with a conjecture").

For satisfiable problems with quantifiers, I would use `--finite-model-find`.  This enables techniques from this paper: https://homepage.divms.uiowa.edu/~ajreynol/cade24.pdf 
Unfortunately these techniques are not enabled by default either since they degrade the performance of cvc5 for unsatisfiable problems.

Btw, another option to consider is `--use-portfolio`, which internally runs a set of options based on a fixed strategy internally.
