### ISSUE TITLE
feature request: is_decimal

### ISSUE THREAD

**Issue by florianschanda** [cvc5/cvc5#9868]
Hi, I have a source language where the user can write infinite precision decimals; but in expressions everything is evaluated as rationals.

Right now I am modelling this with `Real`, but of course something like:
```
   1 / (x + (1 / 3))
```

Gives a counter-example of `x = (-1 / 3)`; but since the user cannot physically assign `(-1/3)` to `x` write that it's actually NOT a real counter-example.

I've experimented with a nasty define-fun-rec is_decimal_denominator function and then defining my reals as rationals; but things are immediately unknown.

Is there an elegant way I can assert that `x` is a decimal?

**Comment by ajreynol** [comment]
If you have an upper bound on the allowed length following the decimal, e.g. `n`, I guess this would be 
`(is_int (* x (^ 10 n)))`?
In other words, multiplying `x` by `10^n` gives some integer value. If `n` is a non-negative value, the above still reduces to linear arithmetic, and should allow any number of non-zero digits following the decimal up to `n`.

If `n` is symbolic, then this is a bit harder since we don't have general support for exponentiation.  Would this be needed for your application?

**Comment by florianschanda** [comment]
There is no maximum precision, but I was thinking of that solution too. The tool doesn't have to be sound so maybe this is good enough.
