### ISSUE TITLE
[Question]: When "error "A non-linear fact was asserted to arithmetic in a linear logic." happens while using "--sygus-rr-synth-input"?

### ISSUE THREAD

**Issue by hagozaebii** [cvc5/cvc5#9941]
Hello, recently, I tried to test `--sygus-rr-synth-input` option in `QF_SLIA`. Even though I did not use non-linear integer function, cvc5 with option `--sygus-rr-synth-input` gave me an error `error "A non-linear fact was asserted to arithmetic in a linear logic.`. I use version 1.0.0

my formula is as follows:
```
(set-logic QF_SLIA)
(declare-fun T_1 () Bool)
(declare-fun T_2 () Bool)
(declare-fun var_0xINPUT_100868 () String)
(assert (= T_1 (not (= "file:" var_0xINPUT_100868))))
(assert (= T_2 (not T_1)))
(assert (str.suffixof (str.from_int (str.indexof (str.replace_re (str.from_code (str.indexof var_0xINPUT_100868 "file:" (- 9))) re.allchar (str.from_code (ite T_1 (- 8) (- 3)))) (str.from_code (- (- 9) (+ (- 2) 7))) (str.indexof (str.rev (str.from_code (- 3))) (str.from_code (str.len var_0xINPUT_100868)) (- (str.len var_0xINPUT_100868))))) var_0xINPUT_100868))
(check-sat)
(get-model)
```
And, the assertion I faced is as follows:
```
(error "A non-linear fact was asserted to arithmetic in a linear logic.
The fact in question: (let ((_let_1 (* k_B_80 k_B_80))) (>= (+ (str.indexof """" """" _let_1) (* (- 1) _let_1)) 0))
")
```
Could I know what to do If I wanna avoid the error?
Thanks for reading.

**Comment by ajreynol** [comment]
For now, you can use `(set-logic ALL)`. The `--sygus-rr-synth-input` feature may generate non-linear terms in candidate rewrites.

Btw, this option has been removed in the latest version of cvc5.  You can now use:
`(find-synth :rewrite_input)` instead of `(check-sat)` to invoke this feature, which will return a single rewrite if it can find one, or `--sygus-stream` will output a list similar to the behavior of `--sygus-rr-synth-input`.

**Comment by hagozaebii** [comment]
@ajreynol Thanks for your explanation. I got it right about what you wrote. Thanks again!
